### ISSUE TITLE
Need a sample example for Angular2

### ISSUE THREAD

**Issue by boony862000** [apoterenko/ngx-post-message#4]
Hi,

Im am working on a cross domain communication app and involving iframe in Angular2 

Im trying to use your library.
1. i have created a new project "ng new myapp"
2. installed post message module  "npm i angular2-post-message"
3. included iframe in app.compoment.html which is running on different port.
4. made other changes in app.module.ts

and now im stuck on how i can make communication. can you please able to help

Im only able to logs for "The iframe has sent a message to the parent: LOGOUT" in console.

**Comment by apoterenko** [comment]
See the updated README (+live demo)
