### ISSUE TITLE
Mismatch version?

### ISSUE THREAD

**Issue by mdere** [apoterenko/ngx-post-message#6]
Hello - I am trying to install this library to my Angular 4 app (4.3.1) 

package.json
{
  "name": "-----",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build && mkdir ./dist/help && cp ./src/assets/env.json ./dist/help",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "buildEnv": "mkdir ./dist/help && cp ./src/assets/env.json ./dist/help"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular-font-awesome": "^2.0.3",
    "angular-popper": "^1.0.0-beta-1",
    "bootstrap": "^4.0.0-beta",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "es5-shim": "^4.5.9",
    "es6-shim": "^0.35.3",
    "flexboxgrid": "^6.3.1",
    "immutable": "^3.8.1",
    "jquery": "^3.2.1",
    "ng2-redux": "^5.1.2",
    "ng2-truncate": "^1.3.11",
    "ngx-cookie-service": "^1.0.9",
    "ngx-post-message": "^1.5.3",
    "popper.js": "^1.12.5",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "rxjs": "^5.4.1",
    "sparql-client-2": "^0.6.1",
    "tassign": "^1.0.0",
    "ts-smart-logger": "0.0.4",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.2.7",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "enhanced-resolve": "^3.3.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.5.3",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

And as soon I import it - I get the following upon build:

ERROR in Metadata version mismatch for module C:/workspace/Client/node_modules/ngx-post-message/ngx-post-message.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/workspace/Client/src/app/app.module.ts, resolving symbol AppModule in C:/workspace/Client/src/app/app.module.ts

**Comment by mdere** [comment]
I noticed that "": "^4.0.0", is suppose to be `@angular:`

**Comment by mdere** [comment]
Also now looking at the npm install -

npm WARN ngx-post-message@1.5.3 requires a peer of @angular/core@>=5.0.0 but none was installed.

I thought this library was 4.3.1 compatible?

**Comment by apoterenko** [comment]
Try 1.5.2 (4.x compatible)
